# -*- coding: utf-8 -*-
"""Web_Scraping_HTML_Table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXmdeu515uqKkbOeuonJAw1rVdS6J-2B
"""

#import libraries
from bs4 import BeautifulSoup
import urllib.request

#url
url = 'https://www.w3schools.com/html/html_tables.asp'

#connect to url and parse the page
page = urllib.request.urlopen(url)
soup = BeautifulSoup(page, 'html.parser')
#print(soup)

#table parsing with table id
table = soup.find('table', id= "customers")
row = table.find_all('tr')
print(row)

csv_rows = []
csv_rows.append(['Company', 'Contact', 'Country'])

for r in row:
  data = r.find_all('td')
  if len(data) == 0:
    continue  
  company = data[0].getText()
  contact = data[1].getText()
  country = data[2].getText()
  
  csv_rows.append([company, contact, country])
print(csv_rows)

#generating csv
import csv
with open('html.csv', 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     wr.writerow(csv_rows)